[package]
name = "zumic_examples"
authors = ["Mikhail <mikhail.f.zhuravlev@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
zumic = { path = "../" }

[lints]
workspace = true
